name: Build and deploy Flutter site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
      - name: Unzip starter pack
        run: unzip -q elian_portfolio_flutter_starter.zip
      - name: Install dependencies
        run: |
          cd elian_portfolio_flutter_starter
          flutter pub get
      - name: Build web
        run: |
          cd elian_portfolio_flutter_starter
          flutter build web --release --base-href /elian-portfolio/
      - name: Move built site
        run: mv elian_portfolio_flutter_starter/build/web ./web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
